environment:
  matrix:
  - nodejs_version: "5"
  - nodejs_version: "4"
  - nodejs_version: "0.12"
  - nodejs_version: "0.11"
  - nodejs_version: "0.10"

install:
  - ps: Install-Product node $env:nodejs_version

test_script:
  - node --version
  - npm --version
  - node print | node test

build: off
